# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 06:23
from __future__ import unicode_literals

from django.db import migrations, models
from .. import create_temp_users


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_temp_users.create),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=11)),
                ('duration', models.DecimalField(decimal_places=1, max_digits=6)),
                ('url', models.TextField(null=True)),
            ],
        ),
    ]

