version: '3'

services:
    db:
        build: 
            context: ./
            dockerfile: ./dockerfiles/db

    liftedmobile:
        build:
            context: ./
            dockerfile: ./dockerfiles/liftedmobile
        ports:
            - "80:80"
        expose:
            - "80"
