# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedSalCourse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_new', models.BooleanField()),
                ('name', models.TextField()),
                ('url', models.TextField()),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
            ],
        ),
    ]
