# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 08:28
from __future__ import unicode_literals

from django.db import migrations
from .. import create_temp_users


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_temp_users.create)
    ]
