# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 07:43
from __future__ import unicode_literals

from django.db import migrations, models


def convert_start_date_col(apps, schema_editor):
    ScrapedCourse = apps.get_model("cms", "ScrapedCourse")
    ScrapedCourseDate = apps.get_model("cms", "ScrapedCourseDate")
    db_alias = schema_editor.connection.alias

    # move data from the ScrapedCourse.start_date column to a row
    # in ScrapedCourseDate

    for sc in (ScrapedCourse.objects
               .using(db_alias)
               .filter(start_date__isnull=False)):

        sc_date = ScrapedCourseDate(
            scraped_course=sc,
            start_date=sc.start_date,
            end_date=sc.end_date)

        sc_date.save()

        print("Saved", sc_date.id)


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_create_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedCourseDate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(null=True)),
                ('scraped_course', models.ForeignKey(to="cms.ScrapedCourse",
                                                     on_delete=models.CASCADE)),
            ],
        ),
        migrations.RunPython(convert_start_date_col),
        migrations.RemoveField(
            model_name='scrapedcourse',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='scrapedcourse',
            name='start_date',
        ),
    ]
