version: '3.1'

services:
    db_dev:
        container_name: liftedmobile_db_dev
        build: 
            context: ../
            dockerfile: ./docker/db_dev
        environment:
            - POSTGRES_PASSWORD=password 


    liftedmobile_dev:
        container_name: liftedmobile_dev
        build:
            context: ../
            dockerfile: ./docker/liftedmobile_dev
        volumes:
            - ../src:/src
        ports:
            - "8000:8000"
        expose:
            - "8000"
        environment:
            - DEV=true
            - DB_PWD=password
        logging:
            driver: "awslogs"
            options:
                awslogs-region: "ap-southeast-1"
                awslogs-group: "liftedmobile_logs"
                awslogs-stream: "liftedmobile_stream"
                awslogs-create-group: "true"

    #web:
        #image: busybox
        #logging:
            #driver: "awslogs"
            #options:
                #awslogs-region: "ap-southeast-1"
                #awslogs-group: "liftedmobile_logs"
                #awslogs-stream: "liftedmobile_stream"
                #awslogs-create-group: "true"
