version: '3'

services:
    db:
        container_name: liftedmobile_db
        build: 
            context: ../
            dockerfile: ./docker/db
        environment:
            - POSTGRES_PASSWORD=fGWJTw2Dbpa2p547brXEVjXyzHZu9puytcAaA9mY 

    liftedmobile:
        container_name: liftedmobile
        build:
            context: ../
            dockerfile: ./docker/liftedmobile
        ports:
            - "80:80"
        expose:
            - "80"
        environment:
            - DB_PWD=fGWJTw2Dbpa2p547brXEVjXyzHZu9puytcAaA9mY 
