version: '3'

services:
    db_dev:
        container_name: liftedmobile_db_dev
        build: 
            context: ../
            dockerfile: ./docker/db_dev
        environment:
            - POSTGRES_PASSWORD=password 


    liftedmobile_dev:
        container_name: liftedmobile_dev
        build:
            context: ../
            dockerfile: ./docker/liftedmobile_dev
        volumes:
            - ../src:/src
        ports:
            - "8000:8000"
        expose:
            - "8000"
        secrets:
            - django_secret:
                file: ./secrets/django_secret

        environment:
            - DEV=true
            - DB_PWD=password
