version: '3.1'

services:
    db:
        container_name: admin_db_dev
        build:
            context: ../
            dockerfile: ./dev/db.dev.dockerfile
        environment:
            - POSTGRES_PASSWORD=password

    cms:
        container_name: admin_cms_dev
        build:
            context: ../../../
            dockerfile: ./docker/admin_server/dev/cms.dev.dockerfile
        volumes:
            - ../../../admin_server/cms:/cms
        environment:
            - DB_PWD=password
            - DEV=true
        ports:
            - "9000:9000"

    #scrapyd:
        #container_name: admin_scrapyd_dev
        #build:
            #context: ../
            #dockerfile: ./scrapyd.dockerfile
        #ports:
            #- "80:80"
            #- "443:443"
        #expose:
            #- "80"
            #- "443"
