version: '3.1'

services:
    db:
        container_name: liftedmobile_db
        build: 
            context: ../../
            dockerfile: ./docker/app_server/db.prod.dockerfile
        environment:
            - POSTGRES_PASSWORD=fGWJTw2Dbpa2p547brXEVjXyzHZu9puytcAaA9mY 


    liftedmobile:
        container_name: liftedmobile
        depends_on:
            - "db"
        build:
            context: ../../
            dockerfile: ./docker/app_server/liftedmobile.prod.dockerfile
        expose:
            - "8001"
        volumes:
            - ../../../app_server/django_log:/var/log/django/
        secrets:
            - django_secret
            - django_admin_pwd
            - django_team_pwd
            - django_logging_aws_cw
            - db_config
        logging:
            driver: "awslogs"
            options:
                awslogs-region: "ap-southeast-1"
                awslogs-group: "liftedmobile_logs"
                awslogs-stream: "liftedmobile_stream"
                awslogs-create-group: "true"

    tlsproxy:
        container_name: liftedmobile_tlsproxy
        build:
            context: ../../
            dockerfile: ./docker/app_server/tlsproxy.prod.dockerfile
        ports:
            - "443:443"
            - "80:80"
        volumes:
            - ../../../app_server/tlsproxy/letsencrypt/:/etc/letsencrypt/
        logging:
            driver: "awslogs"
            options:
                awslogs-region: "ap-southeast-1"
                awslogs-group: "liftedmobile_logs"
                awslogs-stream: "liftedmobile_tlsproxy_stream"
                awslogs-create-group: "true"
        secrets:
            - certbot_config
        depends_on:
            - "liftedmobile"

secrets:
    django_secret:
        file: ../../../LM_SECRETS/DJANGO_SECRET
    django_admin_pwd:
        file: ../../../LM_SECRETS/DJANGO_ADMIN_PWD
    django_team_pwd:
        file: ../../../LM_SECRETS/DJANGO_TEAM_PWD
    django_logging_aws_cw:
        file: ../../../LM_SECRETS/DJANGO_LOGGING_AWS_CW.json
    db_config:
        file: ../../../LM_SECRETS/DB_CONFIG.json
    certbot_config:
        file: ../../../LM_SECRETS/CERTBOT_CONFIG.json
