version: '3.1'

services:
    db:
        container_name: liftedmobile_db
        build: 
            context: ../../
            dockerfile: ./docker/app_server/db.prod.dockerfile
        environment:
            - POSTGRES_PASSWORD=fGWJTw2Dbpa2p547brXEVjXyzHZu9puytcAaA9mY 

    liftedmobile:
        container_name: liftedmobile
        build:
            context: ../../
            dockerfile: ./docker/app_server/liftedmobile.prod.dockerfile
        ports:
            - "80:80"
        expose:
            - "80"
        environment:
            - DB_PWD=fGWJTw2Dbpa2p547brXEVjXyzHZu9puytcAaA9mY 
        secrets:
            - django_secret
            - django_admin_pwd
            - django_team_pwd
        logging:
            driver: "awslogs"
            options:
                awslogs-region: "ap-southeast-1"
                awslogs-group: "liftedmobile_logs"
                awslogs-stream: "liftedmobile_stream"
                awslogs-create-group: "true"

secrets:
    django_secret:
        file: ../../../LM_SECRETS/DJANGO_SECRET
    django_admin_pwd:
        file: ../../../LM_SECRETS/DJANGO_ADMIN_PWD
    django_team_pwd:
        file: ../../../LM_SECRETS/DJANGO_TEAM_PWD
