# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 01:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Format',
            fields=[
                ('acronym', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('acronym', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Need',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('question', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NeedFormat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Format')),
                ('need', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Need')),
            ],
        ),
        migrations.CreateModel(
            name='NeedLevel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Level')),
                ('need', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Need')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('acronym', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vertical',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('question', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Funding',
            fields=[
                ('funding_type', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='VerticalCategory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('question', models.TextField()),
                ('vertical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Vertical')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='needlevel',
            unique_together=set([('need', 'level')]),
        ),
        migrations.AlterUniqueTogether(
            name='needformat',
            unique_together=set([('need', 'format')]),
        ),
    ]
