# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 12:29
from __future__ import unicode_literals

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
    ]
