# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 08:27
from __future__ import unicode_literals

from django.db import migrations
from ..lifted_framework_data import extract_framework_data


def load_mvp_data(apps, schema_editor):
    vertical_data = extract_framework_data.parse_verticals()
    print(vertical_data)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_mvp_data)
    ]
