# Production Dockerfile for the admin server
version: '3.1'
networks:
    default:
        external:
            name: appserver_default

services:
    db:
        container_name: admin_db
        build:
            context: ./
            dockerfile: ./db.prod.dockerfile
        environment:
            - POSTGRES_PASSWORD=ko3TnNyBRYVWg3cqgP8G8CTpnmr9HPgndnhpDo98jKGCJwec9H

    cms:
        container_name: admin_cms
        build:
            context: ../../
            dockerfile: ./docker/admin_server/cms.prod.dockerfile
        volumes:
            - ../../../admin_server/django_log:/var/log/django/
        secrets:
            - django_secret
            - cms_admin_pwd
            - scrapyd_api_key
            - django_admin_pwd
            - django_team_pwd
            - django_logging_aws_cw
            - email_credentials
            - admin_emails
            - db_config
        environment:
            - CMS=true
        ports:
            - "9001:80"
        expose:
            - "80"
        logging:
            driver: "awslogs"
            options:
                awslogs-region: "ap-southeast-1"
                awslogs-group: "liftedmobile_logs"
                awslogs-stream: "cms_stream"
                awslogs-create-group: "true"

    scrapyd:
        container_name: admin_scrapyd
        build:
            context: ../../
            dockerfile: ./docker/admin_server/scrapyd.prod.dockerfile
        volumes:
            - ../../../scrapyd/scrapyd:/var/log/scrapyd/
            - ../../../scrapyd/scheduler:/var/log/scraper_scheduler/
        secrets:
            - scrapyd_api_key
        expose:
            - "6800"

secrets:
    django_secret:
        file: ../../../LM_ADMIN_SECRETS/DJANGO_SECRET
    cms_admin_pwd:
        file: ../../../LM_ADMIN_SECRETS/CMS_ADMIN_PWD
    scrapyd_api_key:
        file: ../../../LM_ADMIN_SECRETS/SCRAPYD_API_KEY
    db_config:
        file: ../../../LM_ADMIN_SECRETS/DB_CONFIG.json
    django_admin_pwd:
        file: ../../../LM_SECRETS/DJANGO_ADMIN_PWD
    django_team_pwd:
        file: ../../../LM_SECRETS/DJANGO_TEAM_PWD
    django_logging_aws_cw:
        file: ../../../LM_SECRETS/DJANGO_LOGGING_AWS_CW.json
    email_credentials:
        file: ../../../LM_SECRETS/EMAIL_CREDENTIALS.json
    admin_emails:
        file: ../../../LM_SECRETS/ADMIN_EMAILS.json
