version: '3.1'

services:
    db:
        container_name: admin_db
        build:
            context: ./
            dockerfile: ./db.prod.dockerfile
        environment:
            - POSTGRES_PASSWORD=ko3TnNyBRYVWg3cqgP8G8CTpnmr9HPgndnhpDo98jKGCJwec9H

    cms:
        container_name: admin_cms
        build:
            context: ../../
            dockerfile: ./docker/admin_server/cms.prod.dockerfile
        secrets:
            - django_secret
            - cms_admin_pwd
            - scrapyd_api_key
            - django_admin_pwd
            - django_team_pwd
        environment:
            - CMS=true
            - DB_PWD=ko3TnNyBRYVWg3cqgP8G8CTpnmr9HPgndnhpDo98jKGCJwec9H
        ports:
            - "80:80"
        logging:
            driver: "awslogs"
            options:
                awslogs-region: "ap-southeast-1"
                awslogs-group: "liftedmobile_logs"
                awslogs-stream: "cms_stream"
                awslogs-create-group: "true"

    scrapyd:
        container_name: admin_scrapyd
        build:
            context: ../../
            dockerfile: ./docker/admin_server/scrapyd.prod.dockerfile
        volumes:
            - ../../../scrapyd_logs:/var/log/scrapyd/
            - ../../../scraper_scheduler_logs:/var/log/scraper_scheduler/
        secrets:
            - scrapyd_api_key
        ports:
            - "81:80"
            - "442:443"
            #- "6800:6800"
        expose:
            - "6800"

secrets:
    django_secret:
        file: ../../../LM_ADMIN_SECRETS/DJANGO_SECRET
    cms_admin_pwd:
        file: ../../../LM_ADMIN_SECRETS/CMS_ADMIN_PWD
    scrapyd_api_key:
        file: ../../../LM_ADMIN_SECRETS/SCRAPYD_API_KEY
    django_admin_pwd:
        file: ../../../LM_SECRETS/DJANGO_ADMIN_PWD
    django_team_pwd:
        file: ../../../LM_SECRETS/DJANGO_TEAM_PWD
