# Development Dockerfile for the admin server
version: '3.1'
networks:
    default:
        external:
            name: appserver_default

services:
    db_dev:
        container_name: admin_db_dev
        build:
            context: ./
            dockerfile: ./db.dev.dockerfile
        environment:
            - POSTGRES_PASSWORD=password

    scrapyd_dev:
        container_name: admin_scrapyd_dev
        build:
            context: ../../
            dockerfile: ./docker/admin_server/scrapyd.dev.dockerfile
        volumes:
            - ../../admin_server/scraper:/scraper
        ports:
            - "81:80"
            - "442:443"
            - "6800:6800"
        environment:
            - DEV=true
            - SCRAPYD_API_KEY=scrapydapikey
            - PYTHONUNBUFFERED=1
        expose:
            - "6800"

    cms:
        container_name: admin_cms_dev
        build:
            context: ../../
            dockerfile: ./docker/admin_server/cms.dev.dockerfile
        volumes:
            - ../../src:/src
        environment:
            - DB_PWD=password
            - DEV=true
            - CMS=true
            - PYTHONUNBUFFERED=1
            - LM_DB_HOSTNAME=liftedmobile_db_dev
            - LM_DB_PWD=password
        ports:
            - "9000:9000"
        depends_on:
            - "db_dev"
            - "scrapyd_dev"
